✨ feat: Input 컴포넌트 생성
prgrms-fe-devcourse/FEDC2_2JAVATAYO_Dongyoung pull request #71
Opened 2022-06-10 08:46 UTC by hyunjin0910

: label, input, errorMessage로 구성됨

# 개요

# 작업 내용

# 관련 이슈
close #19 
# 사진

2022-06-10 09:03 UTC, Hyevvy commented on src/components/common/Input/Input.tsx
> +  placeholder: string;
create , edit페이지에서는 placeholder가 필요없을 거 같은데 `placeholder?`로 부탁드려도 될까요 ?? 😮

2022-06-10 09:04 UTC, YuHyun-P commented on src/components/common/Input/Input.tsx
> +      <S.StyledInput
맞습니다 S.StyledInput -> S.Input 으로 변경해야 할 것 같네요

2022-06-11 08:06 UTC, hyunjin0910 commented on src/components/common/Input/Input.tsx
> +  type: string;
비밀번호 같은 경우 type을 password로 넣으면 안보이게 처리가 되어서 넣었는데 특별한경우가 아니면 쓸일이 없을 것 같아서 그냥 default는 text로 해도 좋겠네요
<img width="711" alt="image" src="https://user-images.githubusercontent.com/95457808/173179352-8ac2fdac-d7e9-48fe-b5e6-ba5c128a2ec4.png">

2022-06-11 08:50 UTC, hyunjin0910 commented
새로 추가된 것은 없고 기존 Input을 Input, Label, ErrorMessage 컴포넌트로 분리했습니다
✅  받는 prop이 괜찮은지, 빠진 것은 없는지 중심으로 컨펌 받고 싶습니다

로그인, 회원가입용 Input은 따로 컴포넌트로 제작해서 PR 날리겠습니다

2022-06-11 16:33 UTC, Hyevvy requested changes
고생 많으셨습니당!!
깔끔하게 쪼개주셨네용  ˃̵͈̑ᴗ˂̵͈̑

2022-06-11 16:33 UTC, Hyevvy commented on src/components/common/ErrorMessage/ErrorMessage.tsx
> +  errorMessage?: string;
ErrorMessage 컴포넌트에는 errorMessage랑 error 조건이 필수라고 생각되는데 혹시 어떻게 생각하시나요 .. ?? 😮

2022-06-11 16:33 UTC, Hyevvy commented on src/components/common/Input/Input.tsx
> +      placeholder={placeholder}
placeholder값이 안 넘어왔을 때 처리를 해줘야할 거 같아요 😮
```
 placeholder={placeholder ? placeholder :'없을 때 쓸 값'}
```

2022-06-12 07:17 UTC, YuHyun-P commented on src/components/common/Input/Input.tsx
> +  type: string;
저를 위한 props군요!! type까지 신경 써주시다니 감사합니다👍

2022-06-12 07:29 UTC, YuHyun-P commented on src/components/common/ErrorMessage/ErrorMessage.tsx
> +  errorMessage?: string;
제가 생각하기에는 Input 컴포넌트를 쪼개기 전에는 error 조건이 필수였는데, 쪼개지면서 필수는 아닌 것 같아요!

error조건에 따라서 ErrorMessage 컴포넌트를 **조건부 렌더링**하는 것을 컴포넌트에서 처리할지, 외부에서 처리할지로 나뉠 수 있을 것 같은데 저는 외부에서 처리 하는 것이 가독성 측면에서 좋아보이는데 어떻게 생각하시나요👀

2022-06-12 07:33 UTC, YuHyun-P commented on src/components/common/Input/style.tsx
> +    border-color: #f55139;
저는 사용자가 입력하는 내내 빨간색으로 포커스 되기 보다는 Input 검증 후에 에러가 있을 때 빨간색으로 보여야 할 것 같은데 다들 어떻게 생각하시나요?

2022-06-12 08:01 UTC, Hyevvy commented on src/components/common/ErrorMessage/ErrorMessage.tsx
> +  errorMessage?: string;
아 이런 방법이 더 좋아보이네요 !! 쪼개지면 그렇겠군요 !!

2022-06-12 08:03 UTC, Hyevvy commented on src/components/common/ErrorMessage/ErrorMessage.tsx
> +  errorMessage?: string;
그래도 Error 컴포넌트니까 errorMessage는 필수 아닐까요 ??

2022-06-12 08:05 UTC, Hyevvy commented on src/components/common/Input/style.tsx
> +    border-color: #f55139;
어 좋네용 이게 귀찮으면 그냥 검정색같은 border 를 두껍게 줘도 될거 같아요 !! 😳

2022-06-12 08:09 UTC, hyunjin0910 commented
재오픈

2022-06-12 08:09 UTC, Hyevvy commented
감사합니당 ㅎㅎㅎ

2022-06-12 13:11 UTC, hyunjin0910 commented
## 2차 수정 완료
**Input** 
* type, placeholder 없을 시 처리 추가
* name, value 추가
* width 기본 100%으로 설정
* focus시 Input 창 색상 진하게

**Label**
* prop을 children으로 변경

**ErrorMsg**
* prop을 children으로 변경

2022-06-13 08:07 UTC, YuHyun-P approved these changes
수고하셨습니다!!👍

2022-06-13 09:02 UTC, hyunjin0910 commented
@hwoo3303 @Hyevvy @NamgyungKim 오늘까지 보시고 approve 부탁드립니당

2022-06-13 09:18 UTC, merged